anchor_version = "0.24.2"
solana_version = "1.9.16"

[features]
seeds = true

[scripts]
test = "yarn mocha"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.localnet]
yi = "YiiTopEnX2vyoWdXuG45ovDFYZars4XZ4w6td6RVTFm"

[programs.devnet]
yi = "YiiTopEnX2vyoWdXuG45ovDFYZars4XZ4w6td6RVTFm"

[programs.testnet]
yi = "YiiTopEnX2vyoWdXuG45ovDFYZars4XZ4w6td6RVTFm"

[programs.mainnet]
yi = "YiiTopEnX2vyoWdXuG45ovDFYZars4XZ4w6td6RVTFm"
